#! /bin/zsh

setopt shwordsplit
# List all the languages
langs=`ls *.po`

# Make the apollon.pot file.
cpp_files=$(ls ../*.cpp ../src/*.cpp ../src/*.h | grep -v .moc.cpp)
xgettext -C -ki18n -kI18N_NOOP -ktr2i18n -ktranslate -kaliasLocale -x $KDEDIR/include/kde.pot $cpp_files

rm -rf kyzis.pot
mv -f messages.po kyzis.pot 

# Merge messages for each language
for lang in $langs
do
	echo $lang
	mv $lang $lang.bak
	msgmerge $lang.bak kyzis.pot > $lang
	rm $lang.bak
done

echo "Done."
echo
