
# Hard to believe but the default behaviour of FindQt4.cmake is to have
# QT_QTCORE_LIBRARY set to QT_QTCORE_LIBRARY_RELEASE even if 
# CMAKE_BUILD_TYPE is set to Debug.
#
# I find it more logical to use CMAKE_BUILD_TYPE to decide
# between linking to debug or release version.

if ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
#    message("Qt Linking in debug mode")
    SET( QT_QTCORE_LIBRARY      ${QT_QTCORE_LIBRARY_DEBUG} )
    SET( QT_QTGUI_LIBRARY       ${QT_QTGUI_LIBRARY_DEBUG} )
    SET( QT_QT3SUPPORT_LIBRARY  ${QT_QT3SUPPORT_LIBRARY_DEBUG} )
    SET( QT_QTASSISTANT_LIBRARY ${QT_QTASSISTANT_LIBRARY_DEBUG} )
    SET( QT_QTCORE_LIBRARY      ${QT_QTCORE_LIBRARY_DEBUG} )
    SET( QT_QTDBUS_LIBRARY      ${QT_QTDBUS_LIBRARY_DEBUG} )
    SET( QT_QTDESIGNER_LIBRARY  ${QT_QTDESIGNER_LIBRARY_DEBUG} )
    SET( QT_QTGUI_LIBRARY       ${QT_QTGUI_LIBRARY_DEBUG} )
    SET( QT_QTMOTIF_LIBRARY     ${QT_QTMOTIF_LIBRARY_DEBUG} )
    SET( QT_QTNETWORK_LIBRARY   ${QT_QTNETWORK_LIBRARY_DEBUG} )
    SET( QT_QTNSPLUGIN_LIBRARY  ${QT_QTNSPLUGIN_LIBRARY_DEBUG} )
    SET( QT_QTOPENGL_LIBRARY    ${QT_QTOPENGL_LIBRARY_DEBUG} )
    SET( QT_QTSQL_LIBRARY       ${QT_QTSQL_LIBRARY_DEBUG} )
    SET( QT_QTXML_LIBRARY       ${QT_QTXML_LIBRARY_DEBUG} )
    SET( QT_QTSVG_LIBRARY       ${QT_QTSVG_LIBRARY_DEBUG} )
    SET( QT_QTTEST_LIBRARY      ${QT_QTTEST_LIBRARY_DEBUG} )
    SET( QT_QTMAIN_LIBRARY      ${QT_QTMAIN_LIBRARY_DEBUG} )
    SET( QT_QTUITOOLS_LIBRARY   ${QT_QTUITOOLS_LIBRARY_DEBUG} )
else ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
#    message("Qt Linking in release mode")
    SET( QT_QTCORE_LIBRARY      ${QT_QTCORE_LIBRARY_RELEASE} )
    SET( QT_QTGUI_LIBRARY       ${QT_QTGUI_LIBRARY_RELEASE} )
    SET( QT_QT3SUPPORT_LIBRARY  ${QT_QT3SUPPORT_LIBRARY_RELEASE} )
    SET( QT_QTASSISTANT_LIBRARY ${QT_QTASSISTANT_LIBRARY_RELEASE} )
    SET( QT_QTCORE_LIBRARY      ${QT_QTCORE_LIBRARY_RELEASE} )
    SET( QT_QTDBUS_LIBRARY      ${QT_QTDBUS_LIBRARY_RELEASE} )
    SET( QT_QTDESIGNER_LIBRARY  ${QT_QTDESIGNER_LIBRARY_RELEASE} )
    SET( QT_QTGUI_LIBRARY       ${QT_QTGUI_LIBRARY_RELEASE} )
    SET( QT_QTMOTIF_LIBRARY     ${QT_QTMOTIF_LIBRARY_RELEASE} )
    SET( QT_QTNETWORK_LIBRARY   ${QT_QTNETWORK_LIBRARY_RELEASE} )
    SET( QT_QTNSPLUGIN_LIBRARY  ${QT_QTNSPLUGIN_LIBRARY_RELEASE} )
    SET( QT_QTOPENGL_LIBRARY    ${QT_QTOPENGL_LIBRARY_RELEASE} )
    SET( QT_QTSQL_LIBRARY       ${QT_QTSQL_LIBRARY_RELEASE} )
    SET( QT_QTXML_LIBRARY       ${QT_QTXML_LIBRARY_RELEASE} )
    SET( QT_QTSVG_LIBRARY       ${QT_QTSVG_LIBRARY_RELEASE} )
    SET( QT_QTTEST_LIBRARY      ${QT_QTTEST_LIBRARY_RELEASE} )
    SET( QT_QTMAIN_LIBRARY      ${QT_QTMAIN_LIBRARY_RELEASE} )
    SET( QT_QTUITOOLS_LIBRARY   ${QT_QTUITOOLS_LIBRARY_RELEASE} )
endif ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")


